### ISSUE TITLE
Write J-Unit Tests for both Event Constructors

### ISSUE THREAD

**Issue by mdavis60** [cpe305/fall2016-project-mdavis60#1]
Write a single J Unit test for the default Event Constructor.
Write three test for the other Event Constructor, one for a random date at 12 am, a random date at 12 pm, and a random date at some other time.
Make sure the toString() method works for each case as well.

**Comment by mdavis60** [comment]
I just committed my changes so make sure to get the most recent working copy

**Comment by RAWeber** [comment]
Created a pull request instead of directly committing because your project wasn't correctly loading for me and I could not verify the functionality of these test cases.
